### ISSUE TITLE
Missing rockwool and shulker box recipes

### ISSUE THREAD

**Issue by medsal15** [Hekera/ThermalDyenamics#8]
Dyed rockwools cannot be crafted, and dyed shulker boxes recipes are not shown in JEI. Crafting a dyed shulker box also seems to allow crafting a white shulker box (using [Polymorph](https://modrinth.com/mod/polymorph))

**Comment by JaisDK** [comment]
Which version?

**Comment by medsal15** [comment]
3.0.0, with forge 47.2.6

**Comment by medsal15** [comment]
For the rockwool, it seems the following conditions no longer returns true (and is no longer used by thermal)
```json
{
    "flag": "rockwool",
    "type": "thermal:flag"
}
```

**Comment by JaisDK** [comment]
shulker recipes work, they just don't show in JEI

as for rockwool it seems even thermal themselves are inconsistent in the use of the flag so I'll ask them what's going on with it
