### ISSUE TITLE
Russian Localisation for Dyenamics 1.19.2

### ISSUE THREAD

**Issue by mattervisualizer** [Hekera/ThermalDyenamics#9]
I did it since me and my friends needed it =^)
If you want, you can add it to the mod
![screenshot-0001](https://github.com/JDKDigital/Dyenamics/assets/59848987/18dea067-d276-4bdd-8caf-0e2c2daa8456)
[ru_ru.json](https://github.com/JDKDigital/Dyenamics/files/14764955/ru_ru.json)

**Comment by JaisDK** [comment]
thank you!
